# Generated by Django 5.2.1 on 2025-06-22 19:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteListaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client with Special List',
                'verbose_name_plural': 'Clients with Special Lists',
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='MXN', max_length=3)),
                ('language', models.CharField(default='es', max_length=10)),
                ('activo', models.BooleanField(db_default=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Price List',
                'verbose_name_plural': 'Special Price Lists',
            },
        ),
        migrations.CreateModel(
            name='MargenDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_distribuidor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_vendedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='MXN', max_length=3)),
                ('activo', models.BooleanField(db_default=True, default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor Margin',
                'verbose_name_plural': 'Distributor Margins',
            },
        ),
        migrations.CreateModel(
            name='MargenVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_vendedor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_cliente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Margin',
                'verbose_name_plural': 'Vendor Margins',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_addinteli', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duracion_dias', models.PositiveIntegerField(db_default=30, default=30)),
                ('categoria_servicio', models.CharField(choices=[('movilidad', 'Movilidad'), ('mifi', 'MIFI'), ('hbb', 'HBB')], default='movilidad', help_text='Tipo de servicio asociado: Movilidad, MIFI, HBB.', max_length=20, verbose_name='Service Category')),
                ('moneda', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='MXN', max_length=3)),
                ('language', models.CharField(default='es', max_length=10)),
                ('activo', models.BooleanField(db_default=True, default=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer (Base Catalog)',
                'verbose_name_plural': 'Offers (Base Catalog)',
            },
        ),
        migrations.CreateModel(
            name='OfertaListaPreciosEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cliente_especial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Offer Price',
                'verbose_name_plural': 'Special Offer Prices',
            },
        ),
    ]
