# Generated by Django 5.2.1 on 2025-06-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientelistaasignada',
            name='cliente',
            field=models.OneToOneField(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listapreciosespecial',
            index=models.Index(fields=['moneda', 'activo'], name='idx_list_active_currency'),
        ),
        migrations.AddField(
            model_name='clientelistaasignada',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.listapreciosespecial'),
        ),
        migrations.AddField(
            model_name='margendistribuidor',
            name='distribuidor',
            field=models.ForeignKey(limit_choices_to={'rol': 'distribuidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='margenes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='margenvendedor',
            name='margen_distribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margen_vendedores', to='ofertas.margendistribuidor'),
        ),
        migrations.AddField(
            model_name='margenvendedor',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol': 'vendedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['codigo_addinteli'], name='idx_oferta_code'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['moneda', 'activo'], include=('costo_base',), name='idx_oferta_active_currency'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['categoria_servicio'], name='idx_oferta_categoria_servicio'),
        ),
        migrations.AddField(
            model_name='margendistribuidor',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margenes_distribuidor', to='ofertas.oferta'),
        ),
        migrations.AddField(
            model_name='ofertalistapreciosespecial',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='ofertas.listapreciosespecial'),
        ),
        migrations.AddField(
            model_name='ofertalistapreciosespecial',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.oferta'),
        ),
        migrations.AddIndex(
            model_name='clientelistaasignada',
            index=models.Index(fields=['cliente'], name='idx_client_list'),
        ),
        migrations.AlterUniqueTogether(
            name='clientelistaasignada',
            unique_together={('cliente',)},
        ),
        migrations.AddIndex(
            model_name='margenvendedor',
            index=models.Index(fields=['margen_distribuidor', 'vendedor'], name='idx_vendor_margin_dist_vend'),
        ),
        migrations.AddIndex(
            model_name='margenvendedor',
            index=models.Index(fields=['activo'], name='idx_vendor_margin_active'),
        ),
        migrations.AlterUniqueTogether(
            name='margenvendedor',
            unique_together={('margen_distribuidor', 'vendedor')},
        ),
        migrations.AddIndex(
            model_name='margendistribuidor',
            index=models.Index(fields=['oferta', 'distribuidor'], include=('precio_cliente',), name='idx_margin_dist'),
        ),
        migrations.AlterUniqueTogether(
            name='margendistribuidor',
            unique_together={('oferta', 'distribuidor')},
        ),
        migrations.AddIndex(
            model_name='ofertalistapreciosespecial',
            index=models.Index(fields=['lista', 'oferta'], include=('precio_cliente_especial',), name='idx_special_price'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertalistapreciosespecial',
            unique_together={('lista', 'oferta')},
        ),
    ]
