# Generated by Django 5.2.1 on 2025-06-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriatransaccion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó la acción (admin o sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_transacciones_rel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historialsaldo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario cuyo saldo cambió.', on_delete=django.db.models.deletion.CASCADE, related_name='historial_saldos_rel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='moneda',
            index=models.Index(fields=['codigo'], name='idx_moneda_codigo'),
        ),
        migrations.AddIndex(
            model_name='motivotransaccion',
            index=models.Index(fields=['codigo'], name='idx_motivotrans_codigo'),
        ),
        migrations.AddIndex(
            model_name='motivotransaccion',
            index=models.Index(fields=['activo'], name='idx_motivotrans_activo'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='distribuidor',
            field=models.OneToOneField(help_text='Usuario con rol distribuidor asociado al saldo.', limit_choices_to={'rol': 'distribuidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to=settings.AUTH_USER_MODEL, verbose_name='Distribuidor'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='emisor',
            field=models.ForeignKey(blank=True, help_text='Usuario que inicia la transacción (e.g., admin, distribuidor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_emitidas_rel', to=settings.AUTH_USER_MODEL, verbose_name='Emisor'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='moneda',
            field=models.ForeignKey(help_text='Moneda de la transacción (e.g., MXN, USD).', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_rel', to='transacciones.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='motivo',
            field=models.ForeignKey(blank=True, help_text='Motivo específico de la transacción (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_rel', to='transacciones.motivotransaccion', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='realizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que ejecutó la transacción (admin o sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_transacciones_rel', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='receptor',
            field=models.ForeignKey(blank=True, help_text='Usuario que recibe la transacción (e.g., distribuidor, vendedor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_recibidas_rel', to=settings.AUTH_USER_MODEL, verbose_name='Receptor'),
        ),
        migrations.AddField(
            model_name='historialsaldo',
            name='transaccion',
            field=models.ForeignKey(help_text='Transacción que generó el cambio de saldo.', on_delete=django.db.models.deletion.CASCADE, related_name='historiales_rel', to='transacciones.transaccion', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='auditoriatransaccion',
            name='transaccion',
            field=models.ForeignKey(help_text='Transacción asociada a la acción.', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_rel', to='transacciones.transaccion', verbose_name='Transacción'),
        ),
        migrations.AddIndex(
            model_name='saldo',
            index=models.Index(fields=['distribuidor'], name='idx_saldo_distribuidor'),
        ),
        migrations.AddConstraint(
            model_name='saldo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='saldo_cantidad_no_negativa'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo', 'estado'], name='idx_transaccion_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha_creacion'], name='idx_transaccion_fecha_creacion'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['emisor'], name='idx_transaccion_emisor'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['receptor'], name='idx_transaccion_receptor'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['moneda'], name='idx_transaccion_moneda'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['uuid'], name='idx_transaccion_uuid'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transaccion_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='historialsaldo',
            index=models.Index(fields=['usuario', 'fecha'], name='idx_histsaldo_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialsaldo',
            index=models.Index(fields=['transaccion'], name='idx_histsaldo_transaccion'),
        ),
        migrations.AddConstraint(
            model_name='historialsaldo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_antes__gte', 0)), name='histsaldo_saldo_antes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='historialsaldo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_despues__gte', 0)), name='histsaldo_saldo_despues_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransaccion',
            index=models.Index(fields=['transaccion', 'fecha'], name='idx_audtrans_transaccion_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransaccion',
            index=models.Index(fields=['tipo'], name='idx_audtrans_tipo'),
        ),
    ]
