# Generated by Django 5.2.1 on 2025-06-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbackup',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el respaldo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='asignacionbackup',
            name='distribuidor_anterior',
            field=models.ForeignKey(blank=True, help_text='Distribuidor previamente asignado a la línea.', limit_choices_to={'rol': 'distribuidor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_respaldo', to=settings.AUTH_USER_MODEL, verbose_name='Distribuidor Anterior'),
        ),
        migrations.AddField(
            model_name='linea',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='linea',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro de la línea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='linea',
            name='distribuidor',
            field=models.ForeignKey(blank=True, help_text='Distribuidor responsable de la línea.', limit_choices_to={'rol': 'distribuidor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_distribuidor', to=settings.AUTH_USER_MODEL, verbose_name='Distribuidor'),
        ),
        migrations.AddField(
            model_name='linea',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor asignado a la línea.', limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='asignacionbackup',
            name='linea',
            field=models.ForeignKey(help_text='Línea asociada al respaldo.', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='lineas.linea', verbose_name='Línea'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['msisdn'], name='linea_msisdn_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['iccid'], name='linea_iccid_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['estado'], name='linea_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['distribuidor', 'estado'], name='linea_distribuidor_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['vendedor', 'estado'], name='linea_vendedor_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['fecha_vencimiento_plan'], name='linea_vencimiento_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['portability_status'], name='linea_portability_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['fecha_activacion'], name='linea_activacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='linea',
            constraint=models.CheckConstraint(condition=models.Q(('dias_disponibles__gte', 0)), name='linea_non_negative_dias', violation_error_message='Los días disponibles no pueden ser negativos.'),
        ),
        migrations.AddConstraint(
            model_name='linea',
            constraint=models.UniqueConstraint(fields=('msisdn',), name='linea_unique_msisdn', violation_error_message='El MSISDN ya está registrado.'),
        ),
        migrations.AddConstraint(
            model_name='linea',
            constraint=models.UniqueConstraint(fields=('iccid',), name='linea_unique_iccid', violation_error_message='El ICCID ya está registrado.'),
        ),
        migrations.AddIndex(
            model_name='asignacionbackup',
            index=models.Index(fields=['linea', 'fecha_respaldo'], name='asign_backup_lf_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionbackup',
            index=models.Index(fields=['distribuidor_anterior'], name='asign_backup_d_idx'),
        ),
    ]
