"""
integraciones.apis.constants
---------------------------
Constants for Addinteli API endpoints and error codes as per v8.0 specification.
"""

from typing import Dict

# API endpoints from Addinteli v8.0 (Table 2.1), alphabetized
ENDPOINTS: Dict[str, str] = {
    "ACTIVATION": "/activations",
    "CHANGE_OFFER": "/changeoffer",
    "CHANGE_REGION": "/nirs",  # POST for query, PUT for change
    "CHECK_DEVICE": "/imeis",
    "DISTRIBUTOR_BALANCE": "/distributorbalances",
    "DISTRIBUTOR_INVENTORY": "/dist_inventory",
    "GET_BENEFITS_V2": "/getbenefitsV2",
    "GET_BENEFITS_V3": "/getbenefitsV3",
    "GET_DIGITAL": "/get_digital",
    "LOCK_IMEI": "/lockimei",
    "OPERATION_SEARCH": "/operationsearch",
    "PLANES_DISPONIBLES": "/getplans",  # Note: Requires POST method
    "PORTABILITY": "/portabilities",
    "PRE_ACTIVATION": "/pre_activations",
    "PURCHASE": "/purchases",
    "PURCHASE_EXTENDED": "/cpepurchases",
    "PURCHASE_SEARCH": "/purchasesearch",
    "RESUME": "/resumeB2W",
    "SEND_APN": "/sendapn",
    "SERVICIABILITY": "/serviciability",
    "SET_DIGITAL": "/set_digital",
    "SIM_SWAP": "/simswaps",
    "SUSPEND": "/suspendB2W",
    "UNBARRING": "/unbarringB1W",
    "UNLOCK_IMEI": "/unlockimei",
    "VOICEMAIL_RESET": "/vm_reset",
}

# Error codes from Addinteli v8.0 (Section 3.1), alphabetized by code
ERROR_CODES: Dict[int, str] = {
    1000: "Error desconocido",
    1001: "Parámetro msisdn_iccid no enviado",
    1002: "Parámetro plan_name no enviado",
    1003: "Parámetro name no enviado",
    1004: "Parámetro email no enviado",
    1005: "Parámetro address no enviado",
    1006: "Parámetro distributor_id no enviado",
    1007: "Parámetro wallet_id no enviado",
    1008: "Parámetro coordinates no enviado",
    1009: "No se cuenta con saldo suficiente",
    1010: "Parámetro nip no enviado",
    1011: "NIP inválido",
    1012: "Parámetro port_in no enviado",
    1013: "Port in no corresponde con msisdn_iccid",
    1014: "Parámetro imei no enviado",
    1015: "Parámetro operation no enviado",
    1016: "Parámetro service no enviado",
    1017: "Línea no encontrada",
    1018: "Plan no encontrado",
    1019: "ICCID no pertenece a distribuidor",
    1020: "Línea no pertenece a distribuidor",
    1021: "Línea no se encuentra en estado IDLE",
    1022: "Línea no se encuentra en estado activo",
    1023: "Línea ya fue pre-activada",
    1024: "Cambio de NIR no disponible",
    1025: "ICCID no existe para este distribuidor",
    1026: "Línea no se encuentra suspendida",
    1027: "Línea ya suspendida",
    1028: "Línea no se encuentra bloqueada",
    1029: "Línea bloqueada",
    1030: "Serviciabilidad no disponible para SIMs MIFI",
    1031: "Validación de tipo de servicio de sim y tipo de servicio de plan a activar-comprar",
    1032: "Nueva tipificación asociada a recuperación de número (simswap)",
    1033: "Validación de funciones no compatibles con producto MIFI",
    1034: "Validación de funciones no compatibles con producto MIFI",
    1035: "Validación de funciones no compatibles con producto MIFI",
    1036: "SIM no utilizable por pérdida o daño",
    1037: "La sim ya fue colocada en un dispositivo",
    1038: "Plan de preactivación no encontrado",
    1039: "APN no encontrado",
    1040: "Línea ya se encuentra en estado suspendido",
    1041: "Línea ya se encuentra en estado activo",
    1042: "Cambio de oferta no permitido, no se puede cambiar a la misma oferta",
    1043: "Línea debe tener un plan vigente",
    1044: "No existen ofertas adicionales para esta línea",
    1045: "Solo líneas con planes extendidos pueden adquirir paquetes adicionales",
    1046: "Parámetro no enviado",
    1047: "Parámetro inválido",
    1048: "Error en el sistema",
    1049: "Cambio de oferta no permitido, no se puede cambiar a la misma oferta",
    1050: "Línea debe tener un plan vigente",
    1051: "No existen ofertas adicionales para esta línea",
    1052: "Solo líneas con planes extendidos pueden adquirir paquetes adicionales",
    1053: "Parámetro no enviado",
    1054: "Parámetro inválido",
    1055: "Error en el sistema",
    1056: "Línea no encontrada",
    1057: "Plan no encontrado",
    1058: "ICCID no pertenece a distribuidor",
    1059: "Línea no pertenece a distribuidor",
    1060: "Línea no se encuentra en estado IDLE",
    1061: "Línea no se encuentra en estado activo",
    1062: "Línea ya fue pre-activada",
    1063: "Parámetro coordenadas no enviado",
    1064: "No se cuenta con cobertura para servicios HBB en coordenadas proporcionadas",
}